# permissions to do edit podhealths.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: podhealth-editor-role
rules:
- apiGroups:
  - training.loodse.io
  resources:
  - podhealths
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - training.loodse.io
  resources:
  - podhealths/status
  verbs:
  - get
  - patch
  - update
